--- #YAML:1.0
name:               String-Validator
version:            0.90
abstract:           A Collection of String Validators.
author:
    - John Karr <brainbuz@brainbuz.org>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Email::Address:       1.893
    Email::Valid:         0.185
    Regexp::Common:       2011121001
    String::Validator::Password:  0.9
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
